### ISSUE TITLE
Introduce jdbc support

### ISSUE THREAD

**Issue by evshvarov** [theconst/odm-sample#1]

**Comment by theconst** [comment]
JDBC will require IPC between node.js and JVM. It is really prohibitive in terms of performance and is not necessary (and will require user to install Java to all the infrastructure we already have). 
---
By the way, Evgeny. I have updated the build and release process - now binaries for various platforms and node version are distrubuted in on package. You do not need any c++ related stuff installed now.
Now the sample should be working. Just run
- git pull
- npm isntall
- export DSN="DSN=CacheWinHost"
- npm start 
on your mac.
